version: '3.7'

services:
  customer:
    image: swarmgs/customer
    deploy:
      replicas: 3
  balance:
    image: swarmgs/balance
    ports:
      - 5000:3000
    environment:
      MYWEB_CUSTOMER_API: customer:3000
    deploy:
      replicas: 3
